from algorithm.InsertionLengthAlgorithm import InsertionLengthAlgorithm
from algorithm.PhysicalCoverageAlgorithm import PhysicalCoverageAlgorithm
from algorithm.SequenceCoverageAlgorithm import SequenceCoverageAlgorithm
from algorithm.CigarAlgorithm import CigarAlgorithm
from algorithm.KmersAlgorithm import KmersAlgorithm
